/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bac.com.br.hibernate.modulo.profissiografia;

import bac.com.br.hibernate.Dao.RiscoDao;
import bac.com.br.hibernate.entidade.Funcao;
import bac.com.br.hibernate.entidade.Risco;
import bac.com.br.hibernate.utils.Msg;

/**
 *
 * @author bruno
 */
public class Inserir_riscos extends javax.swing.JDialog {
    
    private Listar_riscos pai;
    Funcao fun;    
    Risco ris;
    private boolean alterar;
    /**
     * Creates new form Inserir_riscos
     */
    public Inserir_riscos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ris = new Risco();
    }
    public Inserir_riscos(Listar_riscos parent, boolean modal) {
        super(parent, modal);
        this.pai = parent;
        initComponents();
        ris = new Risco();
    }
    
    protected void preencher(Risco r){
        ris = r;
        fator.setText(ris.getFatorDeRisco());
        categoria.setText(ris.getCategoria());
        classificacao.setText(ris.getClassificacao());
        intensidade.setText(ris.getIntencidade());
    }
    protected Risco salvar(){
        ris.setFatorDeRisco(fator.getText());
        ris.setCategoria(categoria.getText());
        ris.setClassificacao(classificacao.getText());
        ris.setIntencidade(intensidade.getText());
        ris.setIdCargo(fun);
        
        return ris;
    }  
    
    private void inserir_alterar(){
        if(isAlterar() == true){
            new RiscoDao().alter(salvar());
                Msg.informacao(this, "registro alterado com sucesso");
                pai.atualiza_cargo("");
                dispose();
        }else{
            new RiscoDao().insert(salvar());
                Msg.informacao(this, "registro inserido com sucesso");
                pai.atualiza_cargo("");
                dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fator = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        categoria = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        intensidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        classificacao = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(4, 0, 5, 10));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FATOR DE RISCO:");
        jPanel1.add(jLabel2);

        fator.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel1.add(fator);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TIPO:");
        jPanel1.add(jLabel3);

        categoria.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel1.add(categoria);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("INTENSIDADE:");
        jPanel1.add(jLabel5);

        intensidade.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel1.add(intensidade);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TECNICA:");
        jPanel1.add(jLabel4);

        classificacao.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel1.add(classificacao);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("CADASTRO DE RICOS");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jButton1.setText("SALVAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    inserir_alterar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inserir_riscos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inserir_riscos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inserir_riscos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inserir_riscos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Inserir_riscos dialog = new Inserir_riscos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categoria;
    private javax.swing.JTextField classificacao;
    private javax.swing.JTextField fator;
    private javax.swing.JTextField intensidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the alterar
     */
    public boolean isAlterar() {
        return alterar;
    }

    /**
     * @param alterar the alterar to set
     */
    public void setAlterar(boolean alterar) {
        this.alterar = alterar;
    }
}
