/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bac.com.br.hibernate.modulo.treinamento;

import bac.com.br.hibernate.Dao.DocumentoDao;
import bac.com.br.hibernate.Dao.TreinamentoDao;
import bac.com.br.hibernate.utils.Msg;
import bac.com.br.hibernate.utils.Utils;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author bruno
 */
public class Grafico_por_setores extends javax.swing.JDialog {
    private List<BigInteger> lista_id = new ArrayList<>();
    private List<String> lista_nome = new ArrayList<>();
    private Tela_principal pai;
    
    String min;
    String max;
    /**
     * Creates new form Grafico_por_setores
     */
    public Grafico_por_setores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Utils.maximizar(this);
        atualizacombo();
    }
    public Grafico_por_setores(Tela_principal parent, boolean modal) {
        super(parent, modal);
        this.pai =parent;
        initComponents();
        Utils.maximizar(this);
        atualizacombo();
    }
     private void atualizacombo(){
        cbano.removeAllItems();
        List<String> lista1 = new TreinamentoDao().min();
        min = String.valueOf(lista1.get(0));
        List<String> lista2 = new TreinamentoDao().max();
        max = String.valueOf(lista2.get(0));
        int a = Integer.parseInt(min);
        int b = Integer.parseInt(max);
        cbano.addItem("<...>");
        for(int i = a; i<=b; i++){
            cbano.addItem(String.valueOf(i));
            System.out.println(i);
        }
    }
        public void executar(){
            try {
                lista_id = new DocumentoDao().grafico_setor_valor(cbano.getSelectedItem().toString());
                lista_nome = new DocumentoDao().grafico_setor_nome(cbano.getSelectedItem().toString());
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    
        public void criaGraficoPizza() {
        DefaultCategoryDataset cds = createPieDataset();
        String titulo = " TREINAMENTOS REALIZADOS NO ANO DE "+cbano.getSelectedItem().toString();
        String eixoy = "quantidade";
        String txt_legenda="SETORES";
        boolean legenda = false;
        boolean tooltips = true;
        boolean urls = true;
        JFreeChart grafico = ChartFactory.createBarChart3D(titulo, txt_legenda, eixoy, cds, PlotOrientation.HORIZONTAL, legenda, tooltips, urls);
        ChartPanel myChartPanel = new ChartPanel(grafico, true);
        myChartPanel.setSize(painel.getWidth(), painel.getHeight());
        myChartPanel.setVisible(true);
        painel.removeAll();
        painel.add(myChartPanel);
        painel.revalidate();
        painel.repaint();
    }

    private DefaultCategoryDataset createPieDataset() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        try {
            
            for (int i = 0; i < lista_id.size(); i++) {
                    dataset.setValue(lista_id.get(i), lista_nome.get(i), lista_nome.get(i));
            }
        } catch (Exception e) {
            e.printStackTrace();
            Msg.erro(this, "Erro ao Alimentar o Relatorio \nErro:" + e.getMessage());
        }
        return dataset;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbano = new javax.swing.JComboBox<String>();
        jButton1 = new javax.swing.JButton();
        painel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbano.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbano);

        jButton1.setText("visualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        painel.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(painel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(cbano.getSelectedIndex() == 0){
          Msg.alerta(this, "selecione a opção desejada");
        }else{
           executar();
           criaGraficoPizza();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafico_por_setores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafico_por_setores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafico_por_setores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafico_por_setores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Grafico_por_setores dialog = new Grafico_por_setores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbano;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables
}
