/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bac.com.br.hibernate.modulo.treinamento;

import bac.com.br.hibernate.Dao.TreinamentoDao;
import bac.com.br.hibernate.entidade.Treinamento;
import bac.com.br.hibernate.utils.Msg;
import bac.com.br.hibernate.utils.Utils;
import java.awt.Toolkit;
import static java.lang.Thread.sleep;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author bruno
 */
public class Tela_inicial extends javax.swing.JFrame {

    Treinamento tre;
    /**
     * Creates new form Tela_inicial
     */
    public Tela_inicial() {
        initComponents();
        iniciar();
        tre = new Treinamento();
    }
    // INICIA A TELA E CRIA UMA THREAD PARA O PROGRESSBAR DE INICIALIZAÇÃO

    private void iniciar() {
        INICIAR.setVisible(false);
        Utils.tanscomponente(this);
        try {
            new Thread() {
                public void run() {
                    try {
                        for (int i = 0; i <= 100; i++) {
                            sleep(200);
                            progresso.setValue(i);
                            if (progresso.getValue() <= 40) {
                                descrição.setText("carregando arquivos");
                            }
                            if (progresso.getValue() > 40) {
                                descrição.setText("carregando banco de dados");
                            }
                            if(progresso.getValue() == 90){
                                descrição.setText("atualizando...");
				                Utils.getConexao();
                                //Verificar_vencimentos();
                            }
                            
                            if(progresso.getValue() > 90){
                                descrição.setText("iniciando sistema");
                            }
                        }
                        INICIAR.setVisible(true);
                    } catch (Exception e) {
                        e.printStackTrace();
                        Msg.erro(rootPane, "erro ao iniciar aplicativo");
                    }
                }
            }.start();
            Properties pops = new Properties();
            pops.put("logoString", "CLIPER");
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
            com.jtattoo.plaf.mcwin.McWinLookAndFeel.setCurrentTheme(pops);
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            e.printStackTrace();
            Msg.erro(this, "erro ao setar tema \n" + e.getMessage());
        }
        
    }
    

    

    /**
     * FUNÇÃO DESATIVA POR TER CRIADO SOFTWARE ESPECIFICO PARA ESSA ATIVIDADE
     * 
    private Treinamento alterar() {
        tre.setStatus("ARQUIVADO");
        return tre;
    }
     private void Verificar_vencimentos() {

        try {
            List<BigInteger> listaInt = new ArrayList<BigInteger>();
            List<Treinamento> lista = new TreinamentoDao().atualizar();

            List<Date> listadata = new TreinamentoDao().validade();
            for (Date d : listadata) {
                listaInt.add(new TreinamentoDao().validade(d));
            }
            for (int i = 0; i < listaInt.size(); i++) {
                if (730.0 < listaInt.get(i).doubleValue()) {
                    tre = lista.get(i);
                    new TreinamentoDao().alterar(alterar());
                } else {
                }
            }
        } catch (Exception e) {
            Msg.erro(this, "erro \n" + e.getMessage());
        }
    }
     **/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        progresso = new javax.swing.JProgressBar();
        descrição = new javax.swing.JLabel();
        INICIAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("tela inicial");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(Toolkit.getDefaultToolkit().getImage("c:/treinamento/icone.png"));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bac/com/br/hibernate/imagens/tela_inicial.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(2, 0));
        jPanel2.add(progresso);
        jPanel2.add(descrição);

        INICIAR.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        INICIAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bac/com/br/hibernate/imagens/accept.png"))); // NOI18N
        INICIAR.setText("iniciar");
        INICIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INICIARActionPerformed(evt);
            }
        });
        INICIAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                INICIARKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INICIAR)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INICIAR)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(341, 310));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void INICIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIARActionPerformed
        Tela_login t = new Tela_login();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_INICIARActionPerformed

    private void INICIARKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_INICIARKeyPressed
        Tela_login t = new Tela_login();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_INICIARKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_inicial().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton INICIAR;
    private javax.swing.JLabel descrição;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar progresso;
    // End of variables declaration//GEN-END:variables
}
