/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bac.com.br.hibernate.modulo.treinamento;

import bac.com.br.hibernate.Dao.UsuarioDao;
import bac.com.br.hibernate.entidade.Usuario;
import bac.com.br.hibernate.utils.Loggin;
import bac.com.br.hibernate.utils.Msg;
import bac.com.br.hibernate.utils.TextDocument;
import java.awt.Toolkit;
import java.util.List;

/**
 *
 * @author bruno
 */
public class Cadastrar_usuario extends javax.swing.JDialog {
    private Carregar_usuario pai;
    List<Usuario> lista;
    Usuario us;
    private boolean alterar;

    public boolean isAlterar() {
        return alterar;
    }

    public void setAlterar(boolean alterar) {
        this.alterar = alterar;
    }
    
    
    /**
     * Creates new form Cadastrar_usuario
     */
    public Cadastrar_usuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.iniciar();
        us = new Usuario();
    }
    public Cadastrar_usuario(Carregar_usuario parent, boolean modal) {
        super(parent, modal);
        this.pai = parent;
        initComponents();
        this.iniciar();
        us = new Usuario();
    }
    

    private void iniciar(){
        codigo.setDocument(new TextDocument(50));
        senha.setDocument(new TextDocument(50));   
    }
    private Usuario salvar(){
        us.setCodigo(codigo.getText());
        us.setSenha(senha.getText().toString());
        us.setTipo(tipo.getSelectedItem().toString());
        return us;
    }
    protected void preenche( Usuario u){
        this.us = u;
        codigo.setText(u.getCodigo());
        senha.setText(u.getSenha());
        tipo.setSelectedItem(u.getTipo());
    }

    private boolean validacampos() {
        boolean va = true;
        String vazio = "campos vazios\n";
        if (codigo.getText().equals("")) {
            va = false;
            vazio += "codigo de acesso\n";
        }
        if (senha.getText().equals("")) {
            va = false;
            vazio += "senha";
        }
        if(tipo.getSelectedIndex() == 0){
            va = false;
            vazio += "tipo de usuario";            
        }
        if (va == false) {
            Msg.alerta(this, vazio);
        }
        return va;
    }
    
    private void inserir_alterar(){
        if(validacampos() == true){
            if(isAlterar() == true){
            try {
                new UsuarioDao().alterar(salvar());
                Loggin.arquivo_log("alterado cadastro de um novo usuario com o id"+us.getId()+
                            " com os itens:"+us.getCodigo()+";"+us.getTipo());
                    Msg.informacao(this, "Alterado com sucesso");
            } catch (Exception e) {
                e.printStackTrace();
                Msg.erro(this, "Erro ao alterar o registro \nErro :"+e.getMessage());
            }
        }else{
            try {
                new UsuarioDao().inserir(salvar());
                Loggin.arquivo_log("criado cadastro de um novo usuario com o id"+us.getId()+
                            " com os itens:"+us.getCodigo()+";"+us.getTipo());
                    Msg.informacao(this, "Salvo com sucesso");
            } catch (Exception e) {
                e.printStackTrace();
                Msg.erro(this, "Erro ao salvar o registro \nErro :"+e.getMessage());
            }
        }
        pai.atualiza("");
        dispose();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        codigo = new javax.swing.JTextField();
        senha = new javax.swing.JPasswordField();
        tipo = new componentes.UJComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(Toolkit.getDefaultToolkit().getImage("c:/treinamento/icone.png"));

        jPanel6.setLayout(new java.awt.BorderLayout());

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bac/com/br/hibernate/imagens/disk.png"))); // NOI18N
        jButton1.setText("CADASTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bac/com/br/hibernate/imagens/cancel.png"))); // NOI18N
        jButton3.setText("SAIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jPanel6.add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel4.setLayout(new java.awt.GridLayout(3, 0, 5, 5));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CODIGO:");
        jPanel4.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SENHA:");
        jPanel4.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TIPO:");
        jPanel4.add(jLabel3);

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(3, 0, 5, 5));

        codigo.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel5.add(codigo);

        senha.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel5.add(senha);

        tipo.setEditable(true);
        tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<...>", "ADMINISTRADOR", "COMUM" }));
        tipo.setAutocompletar(true);
        tipo.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel5.add(tipo);

        jPanel2.add(jPanel5);

        jPanel6.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel6, java.awt.BorderLayout.NORTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        inserir_alterar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cadastrar_usuario dialog = new Cadastrar_usuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField senha;
    private componentes.UJComboBox tipo;
    // End of variables declaration//GEN-END:variables
}
